Migrasi Footer Component
reactjs-id/website pull request #13
Opened 2020-10-03 22:41 UTC by hanihusam

Acuan kode dari komponen ini adalah dari [sini](https://github.com/reactjs-id/reactjs.id/blob/master/src/components/layout/Footer.tsx). Saya lihat _library_ Emotion juga _installed_. Jadi, saya mengkombinasikan penggunaan Chakra-ui dengan `styled` dari Emotion.

2020-10-04 02:59 UTC, adibfirman commented
Halo mas, boleh coba implement footernya di file `_app.tsx` kah? biar keliatan gimana tampilannya

2020-10-04 05:12 UTC, hanihusam commented
> Halo mas, boleh coba implement footernya di file `_app.tsx` kah? biar keliatan gimana tampilannya

Oke Mas

2020-10-04 05:39 UTC, adibfirman approved these changes
Legit LGTM 💯 tinggal dari mas @zainfathoni atau mas @resir014

2020-10-04 07:29 UTC, resir014 requested changes
Saya tambahkan review ya. Tolong usahakan pakai style props-nya Chakra UI sebelum di-wrap pake `styled()`.

https://chakra-ui.com/style-props

2020-10-04 07:29 UTC, resir014 commented on components/layout/Footer.tsx
> +  background-color: #111;
Please convert these (padding + colors) to chakra-ui style props.

https://chakra-ui.com/style-props

2020-10-04 07:29 UTC, resir014 commented on components/layout/Footer.tsx
> +    color: #fff;
Please use chakra-ui style props instead.

https://chakra-ui.com/style-props

2020-10-04 07:29 UTC, resir014 commented on components/layout/Footer.tsx
> +const Inner = styled(Stack)`
Please convert these to chakra-ui style props.

https://chakra-ui.com/style-props

2020-10-05 15:10 UTC, adibfirman commented on pages/_app.tsx
> +        <Footer />
ohh iya btw ini boleh minta tolong pindahin ke `components/Page` aja ya mas, thanks mas 👌

2020-10-06 02:40 UTC, hanihusam commented on pages/_app.tsx
> +        <Footer />
Kok enggak bisa Resolve Conflict ya Mas @adibfirman

2020-10-06 07:12 UTC, resir014 approved these changes

2020-10-06 08:01 UTC, merged

2020-10-06 08:02 UTC, resir014 commented
@hanihusam Sudah saya bantu buat resolve conflict ya, sebelum dimerge.

Sudah saya hapus juga `package-lock.json`, karena kita pake yarn, **bukan npm**.