chore(top-navigation): migrasi top-navigation
reactjs-id/website pull request #16
Opened 2020-10-04 13:04 UTC by SamX23

Migrasi komponen TopNavigation dari [sini](https://github.com/reactjs-id/reactjs.id/blob/master/src/components/layout/TopNavigation.tsx), beserta logo dan pengaplikasian di top level komponen _app.tsx

- Masih menggunakan css module (Butuh review jika harus diganti ke chakra kah ?)
- props title belum dinamis

Mohon review dan saranya mas @adibfirman siap menerima perubahan.

2020-10-04 13:35 UTC, adibfirman commented
Halo,
Boleh di fix gak error yang terdapat di CI?

Makasih

2020-10-04 14:00 UTC, SamX23 commented
Siap sudah mas

2020-10-04 14:08 UTC, adibfirman commented on components/Layout/TopNavigation.module.css
> +.root {
kalau bisa kita udah gak pakai `*.module.css` lagi ya, jadi ambil dari Chakra UI semua
https://chakra-ui.com/style-props

2020-10-04 14:09 UTC, adibfirman commented on components/Layout/TopNavigation.tsx
> +    <ul className={style.Inner}>
ganti ke https://chakra-ui.com/list yaa

2020-10-04 14:19 UTC, adibfirman reviewed
Minta tolong di cek ulang ya mas, dan ada beberapa yang kyknya harus dijelaskan, Terima kasih mas 🙏

2020-10-04 14:19 UTC, adibfirman commented on components/Layout/TopNavigation.tsx
> +import customColors from '../../utils/theme'
ubah ke alias import aja mas mas jadi `~/utils/theme`

2020-10-04 14:19 UTC, adibfirman commented on package.json
> +    "polished": "^3.6.7",
boleh tau library ini untuk apa?

2020-10-04 14:19 UTC, adibfirman commented on pages/_app.tsx
> +import customColors from '../utils/theme'
tolong ganti ke alias import ya `~/utils`

2020-10-04 14:19 UTC, adibfirman commented on pages/_app.tsx
> +  const TopNavigationShellFallback = styled('div')`
ini fallback maksudnya untuk apa ya mas?

2020-10-04 14:31 UTC, SamX23 commented on package.json
> +    "polished": "^3.6.7",
Itu lib buat manggil fungsi transparentize, tadinya pake test buat styling background color headernya mas. Tapi karena pake css module, lupa hapus habis testing, saya revisi. Terima kasih

2020-10-04 14:34 UTC, SamX23 commented on pages/_app.tsx
> +  const TopNavigationShellFallback = styled('div')`
Saya pikir itu untuk menangani styling untuk jaga jaga biar ga keload, saya revisi mas, terima kasih

2020-10-04 18:32 UTC, resir014 requested changes
@SamX23 Tolong file `package-lock.json` dihapus. Kita pakai `yarn`, bukan `npm`.

2020-10-05 07:58 UTC, SamX23 commented
Halo,
Mas @adibfirman udh di migrasi ke chakra-ui, dan beberapa kode sudah dibenahi, mohon bantuan reviewnya.

Cc mas @resir014 `package-lock.json` sudah di hapus.

Terima kasih.

2020-10-05 10:21 UTC, resir014 requested changes
Ada satu lagi:

2020-10-05 12:53 UTC, SamX23 commented on pages/_app.tsx
> +      <TopNavigation title="ReactJS ID" />
![image](https://user-images.githubusercontent.com/44131347/95081690-1962ad80-0744-11eb-8058-37594a6c6d8f.png)

![image](https://user-images.githubusercontent.com/44131347/95081886-6cd4fb80-0744-11eb-9c81-fd6cb5c1d9df.png)

Waktu dipindah ke komponen `Layout/Page.tsx` sebelum {children}, headernya jadi ga muncul di halaman 404, by default seharusnya dimunculin atau memang tanpa header footer mas @resir014 ?

2020-10-05 15:06 UTC, adibfirman commented on pages/_app.tsx
> +      <TopNavigation title="ReactJS ID" />
by default emang tanpa header dan footer kok mas, karena file `404` belum ada

2020-10-05 18:27 UTC, SamX23 commented
Sudah dibenahi lagi mas.
Tambahan pake komponen NextChakraLink dari [sini](https://github.com/chakra-ui/chakra-ui/blob/develop/examples/nextjs-typescript/components/NextChakraLink.tsx) karena untuk styling komponen `Link` punya Chakra-ui harus digabung sama `Link` punya next, jadi itu solusinya lebih simple.

Kalo ada masukan lain siap saya edit lagi, terima kasih.

2020-10-06 06:41 UTC, resir014 requested changes
Satu lagi buat `NextChakraLink`:

2020-10-06 06:41 UTC, resir014 commented on components/Layout/NextChakraLink.tsx
> +    <NextLink passHref={true} href={href} as={as} replace={replace} scroll={scroll} shallow={shallow} prefetch={prefetch}>
```suggestion
    <NextLink passHref href={href} as={as} replace={replace} scroll={scroll} shallow={shallow} prefetch={prefetch}>
```

Kalau `true` gak usah dikasih isi prop-nya. Kalau pake atribut doang dia akan default ke `true`.

2020-10-06 06:41 UTC, resir014 commented on components/Layout/NextChakraLink.tsx
> +export const NextChakraLink = ({ href, as, replace, scroll, shallow, prefetch, children, ...chakraProps }: NextChakraLinkProps) => {
```suggestion
export function NextChakraLink({ href, as, replace, scroll, shallow, prefetch, children, ...chakraProps }: NextChakraLinkProps) {
```

Convert ke `function`.

2020-10-06 06:53 UTC, SamX23 commented on components/Layout/NextChakraLink.tsx
> +    <NextLink passHref={true} href={href} as={as} replace={replace} scroll={scroll} shallow={shallow} prefetch={prefetch}>
Ini udh di update mas di commit terbaru

2020-10-06 08:11 UTC, resir014 commented
@SamX23 Tolong dibantu resolve merge conflicts ya.

2020-10-06 10:44 UTC, resir014 requested changes
Tolong dibantu resolve merge conflicts ya. @SamX23

2020-10-06 10:49 UTC, adibfirman reviewed
Legit 💯

2020-10-06 10:50 UTC, resir014 approved these changes
Eh ternyata udah di-resolve merge conflicts-nya. Disregard my last comment, LGTM. 👍

2020-10-06 10:51 UTC, merged