chore: migrate a home page
reactjs-id/website pull request #26
Opened 2020-10-10 07:19 UTC by adibfirman

Migrating a home page, and create a new component and its called `LinkButton`

2020-10-12 13:41 UTC, adibfirman commented
@resir014 yang lihat selengkapnya ku belum masukin path `/learning` sih it's okay, isn't it?

2020-10-13 02:31 UTC, resir014 requested changes
Ada changes, mostly buat nyesuaiin font size sama line height aja:

2020-10-13 02:31 UTC, resir014 commented on pages/index.tsx
>          welcomeMessage="selamat datang"
```suggestion
        welcomeMessage="Selamat Datang"
```
Proper capitalisation.

2020-10-13 02:31 UTC, resir014 commented on pages/index.tsx
> +              kabar gembira!
```suggestion
              Kabar Gembira!
```

Proper capitalisation.

2020-10-13 02:31 UTC, resir014 commented on pages/index.tsx
> +            ingin belajar react?
```suggestion
            Ingin Belajar React?
```

Proper capitalisation.

2020-10-13 02:31 UTC, resir014 commented on pages/index.tsx
> +          <Heading as="h3" fontSize="48px" lineHeight="56px">
```suggestion
          <Heading as="h3" fontSize="md" fontWeight={600}>
```

Font weight should be 600. Proper type scale.

2020-10-13 02:31 UTC, resir014 commented on pages/index.tsx
> +          <Heading as="h2" color="gray08" fontSize="20px" lineHeight="28px" fontWeight={300} textTransform="uppercase">
```suggestion
          <Heading as="h2" color="gray08" fontSize="md" fontWeight={300} textTransform="uppercase">
```

Use consistent type scale.

2020-10-13 02:31 UTC, resir014 commented on pages/index.tsx
> +            <Heading as="h3" fontSize="2.86rem" fontWeight={600}>
```suggestion
            <Heading as="h3" fontSize="2xl" fontWeight={600}>
```

Consistent font size.

2020-10-13 02:31 UTC, resir014 commented on pages/index.tsx
> +            <Heading as="h2" fontSize="xl" fontWeight={300} textTransform="uppercase">
```suggestion
            <Heading as="h2" fontSize="md" fontWeight={300} textTransform="uppercase">
```

Proper type scale.

2020-10-13 02:31 UTC, resir014 commented on pages/index.tsx
> +                        Kunjungin Situs
```suggestion
                        Kunjungi Situs
```

`Kunjungin` -> `Kunjungi`

2020-10-13 14:49 UTC, adibfirman commented
Thanks @resir014 , ku udah coba update dengan type-scale

2020-10-15 11:37 UTC, resir014 approved these changes

2020-10-15 11:38 UTC, merged