add LearningPage
reactjs-id/website pull request #27
Opened 2020-10-21 01:36 UTC by yuhanasy

Migrating LearningPage and create some components that needed for the structure of the page.

2020-10-21 14:00 UTC, adibfirman reviewed
Aku ada sedikit review aja sih, thanks mas 🙏

2020-10-21 14:00 UTC, adibfirman commented on components/learning/LearningCard.tsx
> +import * as React from 'react'
Kalau bisa `LearningCart` ini samain aja sama kayak yang di HomePage, berarti bagian `LearningCart` di homepage yang dijadikan component disini

2020-10-21 14:00 UTC, adibfirman commented on content/learning.json
> +[
file ini udah ada mas, di `resources/learning.json`

2020-10-21 14:00 UTC, adibfirman commented on pages/learning.tsx
> +import LearningSection from '../components/learning/LearningSection'
kalau bisa LearningSection jangan di taro di `components` folder soalnya itu buat componentns yang bener - benar digunakan lebih dari satu kali, dan juga jangan lupa untuk pakai `path-resolver` supaya tidak ada keluar direktori seperti ini `../`

2020-10-21 22:35 UTC, yuhanasy commented on components/learning/LearningCard.tsx
> +import * as React from 'react'
sebagian component disini sudah saya kerjakan sebelum HomePage yang baru masuk, sip nanti saya update lagi

2020-10-21 22:36 UTC, yuhanasy commented on content/learning.json
> +[
sip

2020-10-21 22:37 UTC, yuhanasy commented on pages/learning.tsx
> +import LearningSection from '../components/learning/LearningSection'
bagusnya ditaroh mana ya? atau langsung di pages/learning nya aja ya?

2020-10-21 23:59 UTC, adibfirman commented on pages/learning.tsx
> +import LearningSection from '../components/learning/LearningSection'
iya untuk sementara langsung aja mas di `pages/learning`

2020-10-24 05:11 UTC, adibfirman requested changes

2020-10-24 05:11 UTC, adibfirman commented on pages/learning.tsx
> +      <LearningSection />
supaya saya dengan yang lain, langsung saja di tempatkan di dalem-nya mas, jadi gak usah di buat component terpisah

```suggestion
<Box as="section" backgroundColor="lightBlue" paddingX="8.5em" paddingY="6em">
      <Grid gap="2px" justifyContent="center" gridAutoFlow="row" textAlign="center">
      ...
      </Grid>
</Box
```

2020-10-26 02:22 UTC, yuhanasy commented on pages/learning.tsx
> +      <LearningSection />
udah updated mas

2020-10-28 05:09 UTC, adibfirman approved these changes
LGTM 💯

2020-10-28 05:09 UTC, merged